# Generated by Django 5.2.1 on 2025-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(blank=True, choices=[('GRP', 'Group'), ('PSN', 'Personal')], null=True),
        ),
    ]
